### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by GustavoMSevero** [dpagliotto/BuscaCEP-Swift-ViaCEP#1]
Hi
I'm trying to run your codes in Swift 3, but get errors
![captura de tela 2017-09-19 as 17 11 23](https://user-images.githubusercontent.com/2678092/30613212-adbcce92-9d5d-11e7-96b9-b9b1d05edf24.png)

**Comment by davidpagliotto** [comment]
Hi Gustavo!
The code was updated to swift 3 and this issues was fixed.
Thank you for to report.
[]s

<img width="950" alt="screen shot 2017-09-22 at 13 16 22" src="https://user-images.githubusercontent.com/12665008/30754208-4790d766-9f98-11e7-8b42-873a0529863d.png">
